// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:firebase_database/firebase_database.dart';
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBtVMO0egGN_1JwchbknTy3ODFJWK17zCA',
    appId: '1:235649527094:web:ef87818c86a9f4ab8f1797',
    messagingSenderId: '235649527094',
    projectId: 'shoppa-93917',
    authDomain: 'shoppa-93917.firebaseapp.com',
    databaseURL: 'https://shoppa-93917-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'shoppa-93917.firebasestorage.app',
    measurementId: 'G-1Z6GG58E89',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBvy7vk2M3mZPDebIpx2YKTHrv68mTyoy0',
    appId: '1:235649527094:android:0a27217df1017b888f1797',
    messagingSenderId: '235649527094',
    projectId: 'shoppa-93917',
    databaseURL: 'https://shoppa-93917-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'shoppa-93917.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBLlMa__cWuvRgClmauhE4813LkDIUDoMk',
    appId: '1:235649527094:ios:b6ba111a7ce59e0e8f1797',
    messagingSenderId: '235649527094',
    projectId: 'shoppa-93917',
    databaseURL: 'https://shoppa-93917-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'shoppa-93917.firebasestorage.app',
    iosClientId: '235649527094-1qij687l6rtf8p2hei566vd3vngae3ra.apps.googleusercontent.com',
    iosBundleId: 'com.example.shoppa',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBLlMa__cWuvRgClmauhE4813LkDIUDoMk',
    appId: '1:235649527094:ios:b6ba111a7ce59e0e8f1797',
    messagingSenderId: '235649527094',
    projectId: 'shoppa-93917',
    databaseURL: 'https://shoppa-93917-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'shoppa-93917.firebasestorage.app',
    iosClientId: '235649527094-1qij687l6rtf8p2hei566vd3vngae3ra.apps.googleusercontent.com',
    iosBundleId: 'com.example.shoppa',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBtVMO0egGN_1JwchbknTy3ODFJWK17zCA',
    appId: '1:235649527094:web:37b35251b08f8f968f1797',
    messagingSenderId: '235649527094',
    projectId: 'shoppa-93917',
    authDomain: 'shoppa-93917.firebaseapp.com',
    databaseURL: 'https://shoppa-93917-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'shoppa-93917.firebasestorage.app',
    measurementId: 'G-LNZFSVTG30',
  );

}